vim.opt.ruler = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.smartcase = true
vim.opt.scrolloff = 4
vim.opt.wildmenu = true
vim.opt.clipboard = "unnamedplus"
vim.opt.cursorline = false
-- vim.opt.swapfile = false
-- vim.opt.backupdir = vim.fn.expand("~/.cache/vim")
-- vim.opt.backupdir = "~/.cache/vim"
vim.opt.encoding = "utf-8"
vim.opt.mouse = "a"
vim.opt.wildmode = "longest,list"
vim.opt.list = true
vim.opt.listchars = "eol:$,tab:>-,trail:~,extends:>,precedes:<"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.foldmethod = "indent"
vim.opt.foldlevel = 99
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.fileformat = "unix"
