require('options')
require('keymaps')
require('plugins')
require('colorscheme')
require('lsp')
require'lspconfig'.pyright.setup{}
require'lspconfig'.clangd.setup{}
require'lspconfig'.lua_ls.setup{}
require'lspconfig'.rust_analyzer.setup{}
require'lspconfig'.bashls.setup{}
